trigger:
- develop
# Task SonarQubePrepare@5: Prepare Analysis Configuration task
# Task MSBuild@1: Build DotNetFramework task
# Task SonarQubeAnalyze@5: Analysis Configuration task
# Task SonarQubePublish@5: Publish Quality Gate Result task
steps:
- task: SonarQubePrepare@5
  inputs:
    SonarQube: SonarQube
    scannerMode: CLI
    cliProjectKey: MBT-2023-003-23001-TrainInspectionProcessOptimization_MBT-2023-003-23001-TrainInspection_develop
    configMode: manual
    extraProperties: sonar.java.binaries=.
- script: |
    FILTERED_PARAMS=$(echo $SONARQUBE_SCANNER_PARAMS | sed 's/"sonar.branch.name":"[^"]*"\,//g' | sed 's/"sonar.pullrequest.branch":"[^"]*"\,//g' | sed 's/"sonar.pullrequest.base":"[^"]*"\,//g' | sed 's/"sonar.pullrequest.key":"[^"]*"\,//g')
    echo "##vso[task.setvariable variable=SONARQUBE_SCANNER_PARAMS]$FILTERED_PARAMS"
  displayName: Filter out non-CE sonar parameters
- task: SonarQubeAnalyze@5
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: 300
