name: Reusable Trivy FS Scan

on:
  workflow_call:
    inputs:
      severity:
        description: 'Severities to fail on'
        required: false
        type: string
        default: 'LOW,MEDIUM,HIGH,CRITICAL'

jobs:
  trivy-vuln-scan:
    name: Trivy Vulnerability Scan (fs)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy filesystem vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          vuln-type: 'os,library'
          severity: ${{ inputs.severity }}
          exit-code: '0'
          format: 'sarif'
          output: 'trivy-vuln.sarif'
          ignore-unfixed: false

      - name: 📄 Mostrar resumo dos findings de vulnerabilidades
        run: |
          echo "=== Trivy Vulnerabilities (SARIF) ==="
          if [[ -s trivy-vuln.sarif ]]; then
            count=$(jq '.runs[].results | length' trivy-vuln.sarif)
            echo "🔍 Total de vulnerabilidades encontradas: $count"
            echo ""
            echo "🧾 Primeiras 50 linhas do SARIF:"
            head -n 50 trivy-vuln.sarif
          else
            echo "⚠️ Arquivo trivy-vuln.sarif está vazio ou não foi gerado corretamente."
          fi

      - name: Upload vuln results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-vuln.sarif'

  trivy-secret-config-scan:
    name: Trivy Secrets & Config Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy config scanner (secrets & misconfigs)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          exit-code: '0'
          format: 'sarif'
          output: 'trivy-config.sarif'

      - name: 📄 Mostrar resumo dos findings de secrets/config
        run: |
          echo "=== Trivy Config/Secrets (SARIF) ==="
          if [[ -s trivy-config.sarif ]]; then
            count=$(jq '.runs[].results | length' trivy-config.sarif)
            echo "🔍 Total de findings (config/secrets): $count"
            echo ""
            echo "🧾 Primeiras 50 linhas do SARIF:"
            head -n 50 trivy-config.sarif
          else
            echo "⚠️ Arquivo trivy-config.sarif está vazio ou não foi gerado corretamente."
          fi

      - name: Upload config results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-config.sarif'
